### PR TITLE
218 cleanup maxcdn sources

### PR DESCRIPTION
**Pull request by rrone**

### CODE REVIEW

**Comment by ahundiak** [comment]
Lot of changes.  Do we really need this vertical tab stuff?  Hate to introduce a dependency on bower if we don't need to.  

Please see if:

npm install https://github.com/dbtek/bootstrap-vertical-tabs --save

Gives you the files you need under node_modules.

**Comment by rrone** [comment]
Ok, I’ll change to this.

rick
310.920.8209
web.ayso@gmail.com

**Comment by rrone** [comment]
Done.  PR#220 <https://github.com/cerad/ng2016/pull/220> updated

rick
310.920.8209
web.ayso@gmail.com

**Comment by ahundiak** [comment]
I'm getting a little confused.  You have two pr's.  One of then seems to
still have bower.json in it?  Not really sure and I might just be tired.

The other one still seems to have some bower related stuff in gulpfile.js?

Any chance you could review and maybe just make one pr?

And why did you remove all those images from Resources/public/images?  Are
they not being used?

**Comment by rrone** [comment]
Sorry for the confusion.

PR #220 fixed all of the CDN sources (218 cleanup maxcdn sources).  I based 219 fix rained out feed on 218 to avoid merge issues.  It became PR #221.

I cancelled #221.  PR #220 contains changes for Issue #218 and Issue #219.  No more bower stuff.  You can see if you read the commits from the bottom of the listed changes.

The images were work-in-process items and are not being used.

rick
310.920.8209
web.ayso@gmail.com

**Comment by ahundiak** [comment]
The gulpfile.js still has a call to bowerComponentsTask(); ?

**Comment by rrone** [comment]
Ok, now I'm tired.  I'll update when i get home.  

rick

**Comment by rrone** [comment]
code cleanup complete

**Pull request merged**
