### PR TITLE
211 assignor search stuck on defaults

### PR DESCRIPTION
**Pull request by rrone**
rebased on 209-fix_selector_layout

### CODE REVIEW

**Comment by rrone** [comment]
for some reason, zayso.css on production was not updated with changes to app.css.

Can you take a look?

rick
310.920.8209
web.ayso@gmail.com

**Comment by ahundiak** [comment]
Just reran gulp-build on the server.  See if that helps.

Also, you need to revert the FilePdfController.  Pdf files are being read
from Resources/public/pdf.  Not the web directory.

**Comment by ahundiak** [comment]
Think your development machine web directory might be getting a bit out of
sync.  Consider deleting all the web/ sub directories then running
gulp-build to get a fresh start.

**Comment by rrone** [comment]
I think it was a cache issue.  Fine now.

I reverted the FilePdfController.  Thought the relative directory was a no-no and we were serving from web/pdf/

rick
310.920.8209
web.ayso@gmail.com

**Pull request merged**
